### ISSUE TITLE
Unable to customize the org face

### ISSUE THREAD

**Issue by UncleAlone** [daviwil/emacs-from-scratch#10]
I got a problem when I try to customize the face for org-mode. It worked for the first time, but when I did `eval-buffer` again. It threw an error (`error: Invalid face, org-level-1`). And now I cannot find any face related to org in `describe-face`. I did some research but still have no idea how to fix it. I hope you can help me with this.

**Comment by JHonaker** [comment]
You're going to have to be more specific than that. What did you change last? What are the relevant pieces of your config that adjust faces or deal with org-mode customizations? Also, this isn't really a problem with anything in the repo. It's probably better suited as a discussion on the Discord.

**Comment by daviwil** [comment]
I believe @UncleAlone got it fixed by adding `(require 'org-faces)` before trying to set the face.  Interesting that this was needed!
