### ISSUE TITLE
Counsel - Bindings (Not helpful)

### ISSUE THREAD

**Issue by nicknapoli82** [daviwil/emacs-from-scratch#16]
I noticed currently we have our **counsel** and **helpful** bindings set in a particular way. I'm wondering if it would be meaningful to move the remap for `describe-function` and `describe-variable` out of the helpful package definition and into counsel.
**FROM**

```lisp
(use-package counsel
  :bind (("C-M-j" . 'counsel-switch-buffer)
         :map minibuffer-local-map
         ("C-r" . 'counsel-minibuffer-history))
  :custom
  (counsel-linux-app-format-function #'counsel-linux-app-format-function-name-only)
  :config
  (counsel-mode 1))

(use-package helpful
  :custom
  (counsel-describe-function-function #'helpful-callable)
  (counsel-describe-variable-function #'helpful-variable)
  :bind
  ([remap describe-function] . counsel-describe-function)
  ([remap describe-command] . helpful-command)
  ([remap describe-variable] . counsel-describe-variable)
  ([remap describe-key] . helpful-key))

```

**TO**
```lisp
(use-package counsel
  :bind (("C-M-j" . 'counsel-switch-buffer)
         ([remap describe-function] . counsel-describe-function)
         ([remap describe-variable] . counsel-describe-variable)
         :map minibuffer-local-map
         ("C-r" . 'counsel-minibuffer-history))
  :custom
  (counsel-linux-app-format-function #'counsel-linux-app-format-function-name-only)
  :config
  (counsel-mode 1))

(use-package helpful
  :custom
  (counsel-describe-function-function #'helpful-callable)
  (counsel-describe-variable-function #'helpful-variable)
  :bind
  ([remap describe-command] . helpful-command)
  ([remap describe-key] . helpful-key))
```

Just a thought. Since we don't need *helpful* in order to have the counsel bindings still be meaningful.

**Comment by peterpolidoro** [comment]
This seems like a nice change.

I am curious if either of you know of a way for helpful buffer to get shown in a posframe instead of a new window? It would be nice to be able to open a posframe to read and scroll through some help information and then be able to close it and return to the point in the original buffer where the help was invoked.

Thank you so much for such an awesome configuration and video series!
