### ISSUE TITLE
emms mpv/ipc error

### ISSUE THREAD

**Issue by pierceglenn12345** [daviwil/emacs-from-scratch#21]
As a long time emms user on portacle, I find myself running into a unique problem. My machine now runs Ubuntu fresh out of the box as well as a build of the desktop environment described in this video series. After loading an up to date version of emms, music files load perfectly well into an emms *playlist* buffer. However, in playing any one of these files, the minibuffer returns something like "mpv not working: ipc error". I know that we make a call to dbus prior to running emacs in start-exwm.sh, and that there was mention of its use in ipc communications. Is there some hack to correct for what seems to be a communication error? Looking through the internet, I also found this [https://lists.gnu.org/archive/html/emms-help/2018-06/msg00000.html](url) talking about the same error.

Ill admit, I am a (emacs) coder by hobby, and a long time user of org/ledger/emms. Hopefully the answer isn't right in front of my face and I am simply missing it. Thanks for any advice!

**Comment by pierceglenn12345** [comment]
Decided to come back to it today. Removed emms and any config from my system. After reloading the package and adding bare minimum config again, it works! Can't speak to the former issue unfortunately other than user error, most likely.

**Comment by daviwil** [comment]
Hi @pierceglenn12345, I apologize I never got back to you on this!  I'm very glad to hear it's working now though!
