### ISSUE TITLE
Polybar systray icons

### ISSUE THREAD

**Issue by minikN** [daviwil/emacs-from-scratch#26]
I don't know if you mentioned this on stream, but how did you change the icons for the polybar systray?

Talking about icons for `blueman-applet`, `nm-applet`, etc. 

Thanks in advance.

**Comment by daviwil** [comment]
Hey, sorry I missed this!  You have to change your GTK icon theme.  Did you figure out a way to do it?

**Comment by minikN** [comment]
Don't worry about it. All good! You do so much for the community you can't see everything. Yeah I managed to get it to work by installing an icon theme.

Thanks!

**Comment by daviwil** [comment]
Great, glad you got it figured out!
