### ISSUE TITLE
emacs from scratch #1 show notes almost empty

### ISSUE THREAD

**Issue by WillPower3309** [daviwil/emacs-from-scratch#42]
Look like you may have missed adding some parts of https://github.com/daviwil/emacs-from-scratch/blob/master/show-notes/Emacs-01.org

**Comment by daviwil** [comment]
That's basically how they were written at the time!  I know, not very useful.  I was asked to commit all of the show notes I used for the previous episodes so I basically just copied the original files across and checked them in.  Feel free to submit a PR to add anything to it from the episode you think might be helpful!

**Comment by WillPower3309** [comment]
My apologies, misunderstood! Great series by the way, appreciate the help

**Comment by daviwil** [comment]
No worries, thanks a lot!
