### ISSUE TITLE
Error Installing doom-modeline with first init.el

### ISSUE THREAD

**Issue by diazgilberto** [daviwil/emacs-from-scratch#57]
Hi Davi,

Thanks for making these videos. Wanting to jump into emac for a some time now but couldn't find a friendly hand to help. I just finished watch your first video and took the `init.el` file and copy and paste into my `init.el`. Ran `M-x eval-buffer` and getting the following

> I decided to copy and paste your file since I get the same error with mine.

```
Error (use-package): Failed to install doom-modeline: https://melpa.org/packages/all-the-icons-20210425.1035.tar: Not found
Error (use-package): doom-modeline/:init: Symbol’s function definition is void: doom-modeline-mode
Error (use-package): Cannot load doom-modeline
```

**Comment by daviwil** [comment]
Hi @diazgilberto, it looks like your local package index is out of date, try running `M-x package-refresh-contents` and then try installing it again, it should work this time.

**Comment by daviwil** [comment]
To explain a bit more, the reason why I know this is the problem is that the package file is not found in this error:

```
Failed to install doom-modeline: https://melpa.org/packages/all-the-icons-20210425.1035.tar: Not found
```

That's usually because your local package cache is looking for a version of the package that doesn't have a package build on MELPA anymore because there is a newer version.
