### ISSUE TITLE
Missing org-tempo definition after part 7 migration to org config

### ISSUE THREAD

**Issue by zekker6** [daviwil/emacs-from-scratch#7]
At the 7th part there was mention of org-templates package which is apparently missing from resulting org configuration.

Still found it here: https://github.com/daviwil/dotfiles/blob/master/Emacs.org#block-templates

P.S. thanks for awesome videos

**Comment by daviwil** [comment]
Wow, how did I lose that!  I definitely covered it in the episode, I must have deleted it by accident when I was moving things around before committing everything.   Thanks for letting me know!

**Comment by daviwil** [comment]
Fixed now, thanks again!

https://github.com/daviwil/emacs-from-scratch/commit/db440466a0615e14c14cb3b6e629bcb079f91405
