### ISSUE TITLE
Update Cantarell install instruction in Emacs.org

### ISSUE THREAD

**Issue by supermario9590** [daviwil/emacs-from-scratch#9]
In the Emacs.org in this repo, you say

>  I am using the Fira Code and Cantarell fonts for this configuration which will more than likely need to be installed on your machine.

But when I run pacman -R cantarell-fonts on my system, I get

`error: failed to prepare transaction (could not satisfy dependencies)
:: removing cantarell-fonts breaks dependency 'cantarell-fonts' required by gsettings-desktop-schemas
:: removing cantarell-fonts breaks dependency 'cantarell-fonts' required by gtk3`

Meaning that pretty much everyone will have the Cantarell fonts as everyone will probably have gtk3 installed on their system.

**Comment by daviwil** [comment]
Thanks @supermario9590!  If this font is pretty common on distros, I'm glad to hear about it.  I had to install it on my distro Guix, but it's an outlier in things like this.  I'll update the wording to be more accurate.

**Comment by crappydrone** [comment]
Just to let you know that on my Ubuntu 20.04 Cantarell and firacode were not installed by default and had to be installed with

`sudo apt install fonts-cantarell fonts-firacode`

as you first instructed. gtk3 is installed on the system.

Thanks for this very useful series, it has been very helpful as I get back into emacs!

**Comment by daviwil** [comment]
Thanks for confirming @crappydrone!  I'll go ahead and close this for now, seems like maybe the instructions are still necessary.
